server:
  servlet:
    encoding:
      charset: utf-8
      enabled: true
      force: true
  port: 8080
  tomcat:
    threads:
      max: 200
    max-connections: 10000
spring:
  datasource:
    url: jdbc:h2:mem:test;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      default_batch_fetch_size: 100
    open-in-view: false
  output:
    ansi:
      enabled: always

logging:
  level:
    '[org.groom.moongte.jejutanslation]': DEBUG
    '[org.hibernate.type]': TRACE