server:
  port: 80
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    context-path: /api
  tomcat:
    threads:
      max: 200
    max-connections: 10000
spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: Asia/Seoul
    show-sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 30MB
  datasource:
    hikari:
      maximum-pool-size: 30